### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by xiechuanyu** [Bleoo/WindowImageView#1]
- Error:Error converting bytecode to dex:

- Cause: com.android.dex.DexException: Multiple dex files define Lio/github/bleoo/windowimageview/BuildConfig;

- Error:com.android.dex.DexException: Multiple dex files define Lio/github/bleoo/windowimageview/BuildConfig;

**Comment by Bleoo** [comment]
请告知一下，android studio 版本，gradle版本

**Comment by xiechuanyu** [comment]
android3.0 , gradle4.1

**Comment by xiechuanyu** [comment]
是**app**和**window-image-view**这两个module中，都有一个window-image-view包，包名重复了。是不是gradle4.1的问题？

**Comment by xiechuanyu** [comment]
- 是app和window-image-view这两个module中，都有一个window-image-view包，包名重复了。是不是gradle4.1的问题？

- 解决办法：把其中一个包名改了就行。
