### ISSUE TITLE
代码正常运行无报错，但是广告图没有显示 #2

### ISSUE THREAD

**Issue by isliuqihang** [Bleoo/WindowImageView#3]
down下来代码后,能正常运行,但是广告图没有显示.Android版本6.0

**Comment by singlenoah** [comment]
等待很长时间后显示出来了

**Comment by Bleoo** [comment]
本地图片 显示也很慢吗

**Comment by singlenoah** [comment]
@Bleoo 是的呢   项目中本地图片在手机上无法显示   我换了张图片后可以正常显示了.
显示网络图片的时候在item完全划出来的时候才显示图片.

**Comment by Bleoo** [comment]
v1.0.2 修复该问题
